export const Projects = [
    {
        key: 0,
        number: "001",
        name: "Interactive Product Tour",
        involvement: ["UI Design", "Front-end Eng", "3D Modeling"],
        company: "Meta Platforms",
        href: 'ipt',
        thumbnail_mobile: '/media/projects/ipt/thumbnail.webp',
        thumbnail_desktop: '/media/projects/ipt/thumbnail.webp',
    },
    {
        key: 1,
        number: "002",
        name: "Scroll To Play",
        involvement: ["UI Design", "Product Design", "Prototyping"],
        company: "Meta Platforms",
        href: 'stp',
        thumbnail_mobile: '/media/projects/stp/thumbnail.webp',
        thumbnail_desktop: '/media/projects/stp/thumbnail.webp',
    },
    {
        key: 2,
        number: "003",
        name: "Comms Portal",
        involvement: ["Product Design", "UX Research", "Front-end Eng"],
        company: "Meta Platforms",
        href: 'cp',
        thumbnail_mobile: '/media/projects/cp/thumbnail.webp',
        thumbnail_desktop: '/media/projects/cp/thumbnail.webp',
    },
    {
        key: 3,
        number: "004",
        name: "Community Voices Hub",
        involvement: ["Product Design", "Front-end Eng", "Motion"],
        company: "Meta Platforms",
        href: 'cv',
        thumbnail_mobile: '/media/projects/cv/thumbnail.webp',
        thumbnail_desktop: '/media/projects/cv/thumbnail.webp',
    },
    {
        key: 4,
        number: "005",
        name: "Meta News Hub",
        involvement: ["Prototyping", "Product Design", "Front-end Eng"],
        company: "Meta Platforms",
        href: 'news',
        thumbnail_mobile: '/media/projects/news/thumbnail.webp',
        thumbnail_desktop: '/media/projects/news/thumbnail.webp',
    },
    {
        key: 5,
        number: "006",
        name: "About Meta Platform",
        involvement: ["Product Design", "Front-end Eng", "UI/UX Design"],
        company: "Meta Platforms",
        href: 'about',
        thumbnail_mobile: '/media/projects/about/thumbnail.webp',
        thumbnail_desktop: '/media/projects/about/thumbnail.webp',
    },
    {
        key: 5,
        number: "007",
        name: "Wavely Job Board",
        involvement: ["Product Design", "Prototyping", "UI/UX Design"],
        company: "Wavely",
        href: 'wavely',
        thumbnail_mobile: '/media/projects/wavely/thumbnail.webp',
        thumbnail_desktop: '/media/projects/wavely/thumbnail.webp',
    },

] 