export const Projects = [
    {
        key: 1,
        number: "001",
        name: "Interactive Product Tour",
        involvement: ["UI Design", "Front-end Eng", "3D Modeling"],
        company: "Meta Platforms",
        href: 'projects/ipt',
        thumbnail: '/media/thumbnails/ipt_thumbnail.webp',
    },
    {
        key: 2,
        number: "002",
        name: "Meta News Platform",
        involvement: ["UI Design", "Product Design", "Prototyping"],
        company: "Meta Platforms",
        href: 'projects/meta-news',
        thumbnail: '/media/thumbnails/news_thumbnail.webp',
    },
    {
        key: 3,
        number: "003",
        name: "Scroll To Play",
        involvement: ["UI Design", "Front-end Eng", "Asset Procurement"],
        company: "Meta Platforms",
        href: 'projects/stp',
        thumbnail: '/media/thumbnails/stp_thumbnail.webp',
    },
    {
        key: 4,
        number: "004",
        name: "Community Voices Hub",
        involvement: ["UI Design", "Front-end Eng", "Prototyping"],
        company: "Meta Platforms",
        href: 'projects/cv',
        thumbnail: '/media/thumbnails/cv_thumbnail.webp',
    },
    {
        key: 5,
        number: "005",
        name: "Metaverse Explainer Site",
        involvement: ["UI Design", "Front-end Eng", "2D Animations"],
        company: "Meta Platforms",
        href: 'projects/metaverse',
        thumbnail: '/media/thumbnails/metaverse_thumbnail.webp',
    },
    {
        key: 6,
        number: "006",
        name: "MTIA v2",
        involvement: ["UI Design", "Front-end Eng", "3D Modeling"],
        company: "Meta Platforms",
        href: 'projects/mtia-v2',
        thumbnail: '/media/thumbnails/mtia_thumbnail.webp',
    },

] 